// screenCandidate({ candidateName, role, experience, skills, availability }) -> result
//
// SCORING (0–100):
//
// Experience (0–40 pts):
//   Parse years: "3 years"->3, "5+ years"->5, "fresher"->0
//   0yrs->5, 1yr->15, 2yrs->25, 3yrs->35, 4+yrs->40
//
// Skills (0–40 pts):
//   Split by comma, each skill = 8pts (max 40)
//   Bonus 5pts if 5+ skills
//
// Availability (0–20 pts):
//   Use parseAvailability to count total available hours
//   <4hrs->5, 4–8hrs->10, 8–16hrs->15, >16hrs->20
//
// Status:
//   score>=70 -> "Strong Fit"
//   score>=45 -> "Moderate Fit"
//   score<45  -> "Not Fit"
//
// Returns:
// {
//   score: 78,
//   status: "Strong Fit",
//   summary: "...",
//   strengths: ["...", "..."],
//   gaps: ["...", "..."],
//   recommendation: "...",
//   availabilitySummary: "...",
//   emailBody: "full plain text email for manager"
// }

const { parseAvailability } = require('./parser');

function parseExperience(experience) {
  if (!experience) return 0;
  
  const expStr = experience.toLowerCase();
  
  // Handle "fresher"
  if (expStr.includes('fresher') || expStr.includes('fresh')) {
    return 0;
  }
  
  // Handle "5+ years" or "3 years"
  const match = expStr.match(/(\d+)\+?\s*(?:years?|yrs?)/);
  if (match) {
    return parseInt(match[1]);
  }
  
  return 0;
}

function scoreExperience(years) {
  if (years === 0) return 5;
  if (years === 1) return 15;
  if (years === 2) return 25;
  if (years === 3) return 35;
  return 40; // 4+ years
}

function scoreSkills(skills) {
  if (!skills) return 0;
  
  const skillList = skills.split(',').map(s => s.trim()).filter(s => s);
  const skillCount = skillList.length;
  
  let score = Math.min(skillCount * 8, 40);
  if (skillCount >= 5) {
    score += 5; // Bonus for diverse skill set
  }
  
  return Math.min(score, 40);
}

function scoreAvailability(availability) {
  const slots = parseAvailability(availability);
  
  let totalHours = 0;
  for (const slot of slots) {
    totalHours += (slot.endHour - slot.startHour);
  }
  
  if (totalHours < 4) return 5;
  if (totalHours < 8) return 10;
  if (totalHours < 16) return 15;
  return 20;
}

function screenCandidate({ candidateName, role, experience, skills, availability }) {
  const years = parseExperience(experience);
  const expScore = scoreExperience(years);
  const skillsScore = scoreSkills(skills);
  const availScore = scoreAvailability(availability);
  
  const totalScore = expScore + skillsScore + availScore;
  
  let status;
  if (totalScore >= 70) {
    status = "Strong Fit";
  } else if (totalScore >= 45) {
    status = "Moderate Fit";
  } else {
    status = "Not Fit";
  }
  
  // Generate summary
  const skillList = skills ? skills.split(',').map(s => s.trim()).filter(s => s) : [];
  const availabilitySlots = parseAvailability(availability);
  
  const strengths = [];
  const gaps = [];
  
  if (years >= 3) {
    strengths.push(`Solid ${years}+ years of experience`);
  } else if (years < 2) {
    gaps.push("Limited experience");
  }
  
  if (skillList.length >= 4) {
    strengths.push("Strong technical skill set");
  } else if (skillList.length < 3) {
    gaps.push("Limited skill diversity");
  }
  
  if (availScore >= 15) {
    strengths.push("Excellent availability");
  } else if (availScore < 10) {
    gaps.push("Limited availability");
  }
  
  let recommendation;
  if (status === "Strong Fit") {
    recommendation = "Proceed to interview immediately";
  } else if (status === "Moderate Fit") {
    recommendation = "Consider for interview with additional screening";
  } else {
    recommendation = "Not recommended at this time";
  }
  
  const availabilitySummary = `${availabilitySlots.length} time windows, ${availabilitySlots.reduce((acc, s) => acc + (s.endHour - s.startHour), 0)} hours total`;
  
  // Build email body
  const emailBody = `
SlotSync Candidate Screening Report
=====================================

Candidate: ${candidateName || 'N/A'}
Role: ${role || 'N/A'}

OVERALL SCORE: ${totalScore}/100
STATUS: ${status}

EXPERIENCE: ${expScore}/40 points
- ${years} years (${years === 0 ? 'Fresher' : years < 2 ? 'Junior' : years < 4 ? 'Mid-level' : 'Senior'})

SKILLS: ${skillsScore}/40 points
- ${skillList.join(', ') || 'None listed'}
- ${skillList.length} skills identified

AVAILABILITY: ${availScore}/20 points
- ${availabilitySummary}
- Windows: ${availability || 'None provided'}

STRENGTHS:
${strengths.map(s => `- ${s}`).join('\n') || '- None identified'}

GAPS:
${gaps.map(g => `- ${g}`).join('\n') || '- None identified'}

RECOMMENDATION: ${recommendation}

---
Generated by SlotSync AI Screening
`.trim();
  
  return {
    score: totalScore,
    status,
    summary: `${candidateName} scored ${totalScore}/100 (${status}) with ${years} years experience and ${skillList.length} skills`,
    strengths,
    gaps,
    recommendation,
    availabilitySummary,
    emailBody
  };
}

module.exports = { screenCandidate };
